In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/elective_text_recognize/ЛР2/my_submission.csv', sep=',')
df

Transcription   emotion    Sentiment  \
0    давать успокоиться начало мочь вестись ерунда ...      гнев   негативный   
1    подождать подождать успокоиться пожалуйста под...      гнев   негативный   
2    кристин привет слышать самолёт упасть зеландия...     страх   негативный   
3    кристин привет .. слушать .. бояться лететь ра...     страх   негативный   
4    почему подождать ... подождать давно планирова...    грусть   негативный   
..                                                 ...       ...          ...   
530  готовить медовик приготовить медовик очень вре...  нейтраль  нейтральный   
531  значит правило игра дурак обычный 36 карта кол...  нейтраль  нейтральный   
532  третьяковский галерея продаваться такой игра п...  нейтраль  нейтральный   
533  город челябинск уметь хотеть учиться банкир фи...  нейтраль  нейтральный   
534  звать ленога екатерина 23 год родиться 93-м го...  нейтраль  нейтральный   

     sentiment_digits  emotion_digits  
0                 0.0             0.0  
1                 0.0             0.0  
2                 0.0             3.0  
3                 0.0             3.0  
4                 0.0             1.0  
..                ...             ...  
530               1.0             4.0  
531               1.0             4.0  
532               1.0             4.0  
533               1.0             4.0  
534               1.0             4.0  

[535 rows x 5 columns]

In [ ]:
dictionary_lemma = pd.read_csv('/content/drive/MyDrive/elective_text_recognize/ЛР3/Dictionary_lemmatization_Rus (1).csv', sep= ',')
dictionary_lemma

Word  Sum  Number  Weight
0            аборт -2.0     2.0    -1.0
1       абортивный -1.0     1.0    -1.0
2      абракадабра -1.0     1.0    -1.0
3           абсурд -2.0     2.0    -1.0
4      абсурдность -1.0     1.0    -1.0
...            ...  ...     ...     ...
19632    удивлённо  1.0     1.0     1.0
19633    поражённо  1.0     1.0     1.0
19634  ошеломлённо  1.0     1.0     1.0
19635    ошарашено  1.0     1.0     1.0
19636    изумлённо  1.0     1.0     1.0

[19637 rows x 4 columns]

In [ ]:
vector_list_all = []
for i in range(535):
  string = df['Transcription'].values[i].split(' ')
  vector_list = []
  for k in string:
    for l in range(19637):
      if dictionary_lemma['Word'].values[l] == k:
        vector_list.append(dictionary_lemma.loc[l, 'Weight'])
        break
      if l == 19636:
        vector_list.append(0)
  vector_list_all.append(vector_list)

In [ ]:
vector_list_all[0]

[0,
 1.0,
 0,
 0,
 0,
 -0.9166666666666664,
 0,
 0,
 -1.0,
 0,
 0,
 1.0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

Далее из полученных весов находим следующие параметры и создаем из них вектор.

1. Кол-во положительных слов.
2. Кол-во отрицаильных слов.
3. Среднее значение сентимента всех слов.
4. Максмально положительное значение вектора.
5. Максимально отрицательное значение вектора.

In [ ]:
static_vector = []

for i in vector_list_all:
  static_vector_each = []
  positive_weights = 0
  negative_weights = 0
  avg_sentiment = 0
  count_of_words = len(i)
  max_positive = 0
  max_negative = 0
  for k in i:
    if k > 0:
      positive_weights += 1
    elif k < 0:
      negative_weights += 1
    avg_sentiment += k
    if k > max_positive:
      max_positive = k
    if k < max_negative:
      max_negative = k
  static_vector_each.append(positive_weights)
  static_vector_each.append(negative_weights)
  static_vector_each.append(avg_sentiment/count_of_words)
  static_vector_each.append(max_positive)
  static_vector_each.append(max_negative)
  static_vector.append(static_vector_each)


for i in static_vector:
  print(i)

[2, 2, 0.0026041666666666748, 1.0, -1.0]
[9, 3, 0.10252525252525252, 1.0, -1.0]
[7, 8, -0.02014925373134328, 1.0, -1.0]
[5, 9, -0.035507246376811595, 1.0, -1.0]
[0, 1, -0.1111111111111111, 0, -1.0]
[2, 3, -0.009523809523809521, 1.0, -1.0]
[1, 1, 0.0, 1.0, -1.0]
[1, 2, -0.00555555555555555, 1.0, -1.0]
[0, 0, 0.0, 0, 0]
[3, 0, 0.12, 1.0, 0]
[1, 1, 0.0, 1.0, -1.0]
[2, 0, 0.04411764705882353, 0.8333333333333335, 0]
[0, 2, -0.3333333333333333, 0, -1.0]
[4, 4, 0.013154761904761902, 1.0, -1.25]
[0, 2, -0.6666666666666666, 0, -1.0]
[0, 6, -0.1953125, 0, -1.25]
[1, 2, -0.03333333333333335, 1.0, -1.0]
[0, 1, -0.07692307692307693, 0, -1.0]
[4, 3, 0.04479166666666666, 1.066666666666666, -1.0]
[0, 0, 0.0, 0, 0]
[0, 0, 0.0, 0, 0]
[0, 1, -0.0625, 0, -1.0]
[4, 1, 0.06016260162601624, 1.0, -0.2]
[2, 2, -0.04629629629629628, 1.0, -1.0]
[6, 1, 0.08333333333333325, 1.22222222222222, -1.0]
[2, 3, -0.11111111111111113, 1.0, -1.0]
[0, 2, -0.5, 0, -1.0]
[0, 1, -0.2, 0, -1.0]
[1, 1, 0.0, 1.0, -1.0]
[0, 1, -0.2

In [ ]:
tone_dictionary = pd.DataFrame(static_vector, columns = ['positive', 'negative', 'avg_sentiment', 'max_positive', 'max_negative'])
tone_dictionary

positive  negative  avg_sentiment  max_positive  max_negative
0           2         2       0.002604      1.000000          -1.0
1           9         3       0.102525      1.000000          -1.0
2           7         8      -0.020149      1.000000          -1.0
3           5         9      -0.035507      1.000000          -1.0
4           0         1      -0.111111      0.000000          -1.0
..        ...       ...            ...           ...           ...
530         3         5      -0.001373      1.000000          -1.0
531         1         7      -0.049271      1.000000          -1.0
532         8         5      -0.003929      0.666667          -1.0
533         6         7      -0.010018      1.000000          -1.0
534         8         3       0.046812      1.000000          -1.0

[535 rows x 5 columns]

Мы векторизовали все текста при помощи тонального словаря

Bow


In [ ]:
vectorizer = CountVectorizer()

In [ ]:
corpus = []
for i in range(535):
  string = df['Transcription'].values[i]
  corpus.append(string)

for i in corpus:
  print(i)

давать успокоиться начало мочь вестись ерунда это специально провоцировать человек мочь успокоиться просто человек который договориться подождать подождать стоп стоп заказлить билет месяц назад подождать пожалуйста мочь взять рука мочь взять рука
подождать подождать успокоиться пожалуйста подождать подождать успокоиться умереть 400 человек поездка запланировать ещё месяц назад понимать понимать достаться билет папа .. стоп ... подождать забронировать отель понимать это невозможно вернуть билет стоп ждать поездка год практически обращать внимание этот человек хватить обращать внимание новость ерунда нести мужик вообще взять рука чувство .. успокоиться выпить вода
кристин привет слышать самолёт упасть зеландия мы завтра улетать понимать это вообще ... ... бояться знать делать мочь давать отменить поезка давать сдать билет ... ... слушать мочь успокоиться подождать слушать ерунда провокация ум сойти просто самолёт взять разбиться понимать 400 человек никто выжить понимать смочь .. давать 

In [ ]:
X = vectorizer.fit_transform(corpus).toarray()
bow = pd.DataFrame(X, columns = vectorizer.get_feature_names_out())
bow.tail(6)

10  11  12  15  17  18  20  23  30  36  ...  яковливетить  яковливич  \
529   0   0   0   0   0   0   0   0   0   0  ...             0          0   
530   0   0   0   0   0   0   0   0   0   0  ...             0          0   
531   0   0   0   0   0   0   0   0   0   1  ...             0          0   
532   0   0   0   0   0   0   0   0   0   0  ...             0          0   
533   0   0   0   0   0   0   0   0   0   0  ...             1          0   
534   0   0   0   0   0   0   0   1   0   0  ...             0          0   

     ялта  январь  яндекс  ярмарка  ясно  яхта  яхточка  ёлка  
529     0       0       0        0     0     0        0     0  
530     0       0       0        0     0     0        0     0  
531     0       0       0        0     0     0        0     0  
532     0       0       0        0     0     0        0     0  
533     0       0       0        0     0     0        0     0  
534     0       1       0        0     0     0        0     0  

[6 rows x 3126 columns]

TFIDF

In [ ]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus).toarray()
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
tfidf = pd.DataFrame(X, columns = vectorizer.get_feature_names_out())
tfidf

10   11   12   15   17   18   20        23   30        36  ...  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.000000  ...   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.000000  ...   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.000000  ...   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.000000  ...   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.000000  ...   
..   ...  ...  ...  ...  ...  ...  ...       ...  ...       ...  ...   
530  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.000000  ...   
531  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.101637  ...   
532  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.000000  ...   
533  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.000000  0.0  0.000000  ...   
534  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.147437  0.0  0.000000  ...   

     яковливетить  яковливич  ялта   январь  яндекс  ярмарка  ясно  яхта  \
0        0.000000        0.0   0.0  0.00000     0.0      0.0   0.0   0.0   
1        0.000000        0.0   0.0  0.00000     0.0      0.0   0.0   0.0   
2        0.000000        0.0   0.0  0.00000     0.0      0.0   0.0   0.0   
3        0.000000        0.0   0.0  0.00000     0.0      0.0   0.0   0.0   
4        0.000000        0.0   0.0  0.00000     0.0      0.0   0.0   0.0   
..            ...        ...   ...      ...     ...      ...   ...   ...   
530      0.000000        0.0   0.0  0.00000     0.0      0.0   0.0   0.0   
531      0.000000        0.0   0.0  0.00000     0.0      0.0   0.0   0.0   
532      0.000000        0.0   0.0  0.00000     0.0      0.0   0.0   0.0   
533      0.126743        0.0   0.0  0.00000     0.0      0.0   0.0   0.0   
534      0.000000        0.0   0.0  0.12694     0.0      0.0   0.0   0.0   

     яхточка  ёлка  
0        0.0   0.0  
1        0.0   0.0  
2        0.0   0.0  
3        0.0   0.0  
4        0.0   0.0  
..       ...   ...  
530      0.0   0.0  
531      0.0   0.0  
532      0.0   0.0  
533      0.0   0.0  
534      0.0   0.0  

[535 rows x 3126 columns]

Сохраняем полученные результаты

In [ ]:
tone_dictionary.to_csv('/content/drive/MyDrive/elective_text_recognize/ЛР3/tone_dictionary.csv', index=False)
bow.to_csv('/content/drive/MyDrive/elective_text_recognize/ЛР3/bow_vectorized.csv', index=False)
tfidf.to_csv('/content/drive/MyDrive/elective_text_recognize/ЛР3/tfidf_vectorized.csv', index=False)